### ISSUE TITLE
Return orbital graphs with only base pairs chosen from `MovedPoints(G)`

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/OrbitalGraphs#22]
Currently `OrbitalGraphs` makes orbital graphs for all base pairs in `[1 .. LargestMovedPoint(G)]`. This means if you have the group `<(3,4)>`, for instance, you get some arguably silly orbital graphs, like the one just containing the edge `[1,2]`, and the one containing just the edges `[1,3], [1,4]`.

I don't see any point in returning these ones, but perhaps I am missing something? If not, I think we should only choose base pairs from `MovedPoints(G)`.

**Comment by ChrisJefferson** [comment]
I would only do MovedPoints(G).

Also, doing [1..LargestMovedPoint(G)] means that (for example) you would calculate the normalizer of Group((2,3)) in SymmetricGroup(4) "wrong", as you would get orbital graphs which involve 1, but not ones which involve 4. Just only working on MovedPoints(G) feels like the easiest way to fix this.

**Comment by wilfwilson** [comment]
I understand and agree. The currently bug reported in #19 is that `OrbitalGraphs` is actually currently using `[1 .. NrMovedPoints(G)]`, which is even worse. But instead of moving to `[1..LargestMovedPoint(G)]`, I'll maybe moved directly to using `MovedPoints(G)`.
